### ISSUE TITLE
8. Add mutation

### ISSUE THREAD

**Issue by richelbilderbeek** [JeroenN/Spatial-model#9]
When creating offspring, initially the exact trait value of the parent was used.

Now, the trait value of the offspring equals the trait value of the parent with a [normally distributed mutation](https://github.com/richelbilderbeek/cpp/blob/master/content/CppGetRandomNormal.md ) added.

Example: 

Parameter|Value
---|---
Parent trait|0.5
Mutation rate, mean|0.1
Mutation rate, stddev|0.01
Likely example offspring traits|0.35, 0.4, 0.5, 0.6, 0.65

**Comment by JeroenN** [comment]
`Mutation rate, mean` should be *always* zero, because on average nothing happens. Thanks @richelbilderbeek

**Comment by JeroenN** [comment]
Nonsense! If parent trait equals 0.5 and mutation rate is 0.01, offspring traits should remain within 0.49 and 0.51 in 68% of all cases. Thanks @richelbilderbeek
